GET http://localhost:3001/api/country HTTP/1.1


###

GET http://localhost:3001/api/country/home HTTP/1.1


###

POST http://localhost:3001/api/country HTTP/1.1
Content-Type:  application/json

{
    "id_letters" : "FRe", 
    "name": "France", 
    "image": "imagen", 
    "continent": "Europe", 
    "subregion": "nueva Europa", 
    "capital": "pepe", 
    "area": 4562132, 
    "population": 45612847
}

###

POST http://localhost:3001/api/country HTTP/1.1
Content-Type:  application/json

{
    "id_letters" : "FRe", 
    "name": "Franciel", 
    "image": "imagen", 
    "continent": "Europe", 
    "subregion": "nueva Europa", 
    "capital": "pepe", 
    "area": 4562132, 
    "population": 45612847
}

###

POST http://localhost:3001/api/country HTTP/1.1
Content-Type:  application/json

{
    "id_letters" : "BRZ", 
    "name": "Brazil", 
    "image": "imagen", 
    "continent": "America", 
    "subregion": "surAmerica", 
    "capital": "pepe", 
    "area": 4562132, 
    "population": 45612847
}

###

GET http://localhost:3001/api/country/china HTTP/1.1


###

GET http://localhost:3001/api/country/id/2900f9f0-a964-487e-9a78-1f2a571fcab0 HTTP/1.1



###



GET http://localhost:3001/api/tourism HTTP/1.1


###

POST  http://localhost:3001/api/tourism HTTP/1.1
Content-Type:  application/json

{ 
    "name" : "surf", 
    "dificulty": 4, 
    "duration": 60, 
    "season": "summer"
}

###

POST  http://localhost:3001/api/tourism HTTP/1.1
Content-Type:  application/json

{ 
    "name" : "boiling", 
    "dificulty": 2, 
    "duration": 120, 
    "season": "winter"
}

###

POST http://localhost:3001/api/tourism/1/country/2900f9f0-a964-487e-9a78-1f2a571fcab0 HTTP/1.1


###

POST http://localhost:3001/api/tourism/1/country/167ece74-0c9b-4fdc-9ef3-b04b7d8dd546 HTTP/1.1

