GET http://localhost:3001/api/country HTTP/1.1


###

GET http://localhost:3001/api/country/home HTTP/1.1


###

POST http://localhost:3001/api/country HTTP/1.1
Content-Type:  application/json

{
    "id_letters" : "FRe", 
    "name": "France", 
    "image": "imagen", 
    "continent": "Europe", 
    "subregion": "nueva Europa", 
    "capital": "pepe", 
    "area": 4562132, 
    "population": 45612847
}

###

POST http://localhost:3001/api/country HTTP/1.1
Content-Type:  application/json

{
    "id_letters" : "FRe", 
    "name": "Franciel", 
    "image": "imagen", 
    "continent": "Europe", 
    "subregion": "nueva Europa", 
    "capital": "pepe", 
    "area": 4562132, 
    "population": 45612847
}

###

POST http://localhost:3001/api/country HTTP/1.1
Content-Type:  application/json

{
    "id_letters" : "BRZ", 
    "name": "Brazil", 
    "image": "imagen", 
    "continent": "America", 
    "subregion": "surAmerica", 
    "capital": "pepe", 
    "area": 4562132, 
    "population": 45612847
}

###

GET http://localhost:3001/api/country/456 HTTP/1.1


###

GET http://localhost:3001/api/country/id/5ab8a454-15f3-4ec2-9a61-87bcbd50f338 HTTP/1.1



###

###

GET http://localhost:3001/api/tourism HTTP/1.1


###

POST  http://localhost:3001/api/tourism HTTP/1.1
Content-Type:  application/json

{ 
    "name" : "surf", 
    "dificulty": 4, 
    "duration": 60, 
    "season": "summer"
}

###

POST  http://localhost:3001/api/tourism HTTP/1.1
Content-Type:  application/json

{ 
    "name" : "boiling", 
    "dificulty": 2, 
    "duration": 120, 
    "season": "winter"
}

###


POST  http://localhost:3001/api/tourism HTTP/1.1
Content-Type:  application/json

{ 
    "name" : "lagata", 
    "dificulty": 2, 
    "duration": 120, 
    "season": "winter"
}

###

POST http://localhost:3001/api/tourism/1/country/830e969a-fd64-493f-a49d-91d692135e30 HTTP/1.1


###

POST http://localhost:3001/api/tourism/2/country/03c4972f-1e0d-4b8b-a517-fc7299d0dc0d HTTP/1.1

